#!/usr/bin/env bash
# Regenerates README.md with a link to every published doc, using each
# HTML file's <title> as the link text. Run from anywhere in the repo.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

BASE_URL="https://marwen-abid.github.io/docs"

{
  echo "# Docs"
  echo
  echo "Published via GitHub Pages at <${BASE_URL}/>."
  echo
  git ls-files '*.html' | sort | while read -r f; do
    title=$(tr '\n' ' ' < "$f" | sed -n 's/.*<title>\([^<]*\)<\/title>.*/\1/p')
    echo "- [${title:-$f}](${BASE_URL}/${f}) — \`${f}\`"
  done
  echo
  echo "_This index is auto-generated by \`scripts/generate-readme.sh\` — do not edit by hand._"
} > README.md
